# Generated by Django 3.2.12 on 2023-08-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=500)),
                ('thumbnailUrl', models.CharField(max_length=100)),
                ('videoUrl', models.CharField(max_length=100)),
            ],
        ),
    ]
